### ISSUE TITLE
Permission to re-license under MIT.

### ISSUE THREAD

**Issue by BramvdKroef** [BramvdKroef/clessc#25]
I'd like to change the license on the c++ LESS compiler from GPL to the more permissive MIT license. Because the project contains contributions from @KamilSzot and @jimstudt I need your permission.

**Comment by KamilSzot** [comment]
Of course. You can release my contributions to your project on whatever license you please.

**Comment by stefan1000** [comment]
Seems like @jimstudt can't be reached via github any longer...

**Comment by jimstudt** [comment]
I’ve been off traveling. Of course, please release my contributions under any license you wish.
