### ISSUE TITLE
Doesnt support rootpath & include path?

### ISSUE THREAD

**Issue by TristanBrotherton** [BramvdKroef/clessc#26]
I'm trying to use the options: --source-map --include-path=./static/ --rootpath=/static/ 

It seems rootpath and include path are not supported?

**Comment by BramvdKroef** [comment]
Yes, those options haven't been implemented.

**Comment by TristanBrotherton** [comment]
Thank you @BramvdKroef for all your hard work. Are these anywhere on your roadmap, or not something you can foresee implementing?
