### ISSUE TITLE
Call to nested mixins fails

### ISSUE THREAD

**Issue by beledouxdenis** [BramvdKroef/clessc#28]
Make a call to a nested mixin will make the compilation fail.

The below less code:
```
.foo () {
    width: 100%;
    height: 100%;
    overflow: auto;

    .nested-foo () {
        padding-top: 20px;
        overflow: auto;

        .nested-nested-foo () {
            float: left;
            position: relative;
            height: 140px;
        }
    }
}

.bar {
    .foo();

    .nested-bar {
        .nested-foo();

        .nested-nested-bar {
            .nested-nested-foo();
        }
    }
}

```
 should return (this is what less.js returns):
```
.bar {
  width: 100%;
  height: 100%;
  overflow: auto;
}
.bar .nested-bar {
  padding-top: 20px;
  overflow: auto;
}
.bar .nested-bar .nested-nested-bar {
  float: left;
  position: relative;
  height: 140px;
}
```
Instead, it returns:
```
Line 21, Column 8 Parse Error: Found ".nested-foo()" when expecting variable, mixin or declaration.
```

**Comment by beledouxdenis** [comment]
Thank you in advance if you solve this. 

This is the last critical point I have. 

After, the remaining issues are really tiny issues:
 - such as the order of the operators in a condition: (`.foo(@index) when (@index < 10+1)`),
 - or the syntax being a bit too strict in some cases: `color : white;` is not accepted, while `color: white;` is.

Thank you !

**Comment by BramvdKroef** [comment]
I've fixed the nested mixin issue and the operator order.

**Comment by beledouxdenis** [comment]
Thank you Bram : )
