### ISSUE TITLE
Issue compiling bootstrap gradient mixins

### ISSUE THREAD

**Issue by TristanBrotherton** [BramvdKroef/clessc#32]
I call Bootstrap 3x gradient mixins in my LESS such as:

`#gradient > .striped(#ddd);`

or:

`#gradient > .radial( darken(@mv-lightGrey, 18%), @mv-lightGrey);`

These will cause CLESSC to fail with: 

```
loading-bar.less: Line 95, Column 6 Parse Error: Found "#gradient > .striped(#ddd)" when expecting variable, mixin or declaration.
```

**Comment by BramvdKroef** [comment]
I've fixed the bug. It should work now.

**Comment by TristanBrotherton** [comment]
Confirmed, now compiles perfectly.
