### ISSUE TITLE
Transpile time greater than node

### ISSUE THREAD

**Issue by TristanBrotherton** [BramvdKroef/clessc#33]
I'm not sure this is really an issue, or an appropriate place for this comment, but I thought I'd ask. I am super excited about this, and really thankful for the effort put into it. 
My main attraction to this was to improve my compile time. 
Currently with NODE my transpile time is around 10 seconds - strangely after compiling CLESSC in my Vagrant environment, and configuring Node to use it, I found it took it to took longer than NODE to transpile my LESS files (about 3x). I wondered if there might be something obvious I was missing?

**Comment by BramvdKroef** [comment]
I've made an update to increase performance.

10 seconds seems really long. On my machine bootstrap compiles in 1.171s with the lesscss.org compiler, 1.067s with clessc before the update and 0.445s after.

**Comment by TristanBrotherton** [comment]
Is there anyway I can provide helpful metrics to you?

I have a very large LESS codebase, which is why things take a while - I was just surprised Node was faster.  I'll give your latest commit a go.

**Comment by TristanBrotherton** [comment]
I've tested with the latest version. The difference is night and day! I'm now compiling our entire application in less than 2seconds - vs 10 seconds with node.

This is a massive improvement, thank you!
