### ISSUE TITLE
Sourcemap URL incorrect (Incorrect file extension)

### ISSUE THREAD

**Issue by TristanBrotherton** [BramvdKroef/clessc#40]
When compiling with LESSC I get the following sourcemap URL generated:

`/*# sourceMappingURL=/static/apps/_/less/ie-fixes.css.map */`

When compiling with CLESSC I get the following:

`/*# sourceMappingURL=/static/apps/_/less/ie-fixes.less.map */`

It appears CLESSC is using the incorrect extension, and it prevents Chrome from finding the sourcemap.

Worth noting I'm invoking both with the option:

`'--source-map-url=/' + outpath + '.map',`

Where outpath is css file. Perhaps this option isn't supported?

**Comment by TristanBrotherton** [comment]
I was able to fix this issue by specifying the outpath in the --sourcemap option:

`'--source-map=/' + outpath + '.map',`

This was different than LESSC which took a specific --source-map-url option:

`'--source-map-url=/' + outpath + '.map',`

**Comment by BramvdKroef** [comment]
They may have changed it recently. Their documentation still states the path is generated from the less filename. I've updated the default source map filename to the output filename with '.map' added.
