### ISSUE TITLE
Rootpath added to protocol relative URLS

### ISSUE THREAD

**Issue by TristanBrotherton** [BramvdKroef/clessc#42]
I specify a rootpath in compilation options of:

`'--rootpath=/static/',`

In LESSC I can specify a protocol relative external URL of:

`background-image: url("//s3.amazonaws.com/image.jpg");`

On compilation this will not have the root path added which is expected. 

In CLESSC this will have the root added resulting in:

`background-image: url("/static///s3.amazonaws.com/image.jpg");`

**Comment by BramvdKroef** [comment]
I've made an update to exclude the rootpath from urls that start with a slash.

**Comment by TristanBrotherton** [comment]
Slash, or double slash?

**Comment by BramvdKroef** [comment]
LESSC doesn't use the rootpath on urls with a single slash, so I've copied that behavior.

**Comment by TristanBrotherton** [comment]
This worked great, thank you.
