### ISSUE TITLE
Nested functions fail

### ISSUE THREAD

**Issue by TristanBrotherton** [BramvdKroef/clessc#43]
Lasted build chokes on these functions:

> background: lighten(fade(@brand-primary, 85%), 10%);
> 
> Parse Error: Found "(" when expecting )

along with bootstrap gradients:

bootstrap/3.3.6/less/mixins/gradients.less: Line 13, Column 115 Parse Error: Found "argb" when expecting valid arguments for function.

**Comment by BramvdKroef** [comment]
The first error is because fade() was not implemented, (I've added it.)
On the second error CLESSC is rejecting the argument because it is not a color. I'll try to make the error more verbose.

**Comment by TristanBrotherton** [comment]
Thanks - this worked great.
